export const duas = [
  {
    slug: 'dua-of-ayyub',
    title: 'Dua of Ayyub عليه السلام',
    category: 'Illness & Endurance',
    arabic: 'أَنِّي مَسَّنِيَ الضُّرُّ وَأَنتَ أَرْحَمُ الرَّاحِمِينَ',
    transliteration: 'Anni massaniya d-durru wa anta arhamur rahimin',
    translationReadable: 'Harm has touched me, and You are the Most Merciful.',
    storyContext: 'Ayyub عليه السلام made this dua during prolonged hardship and illness with patience and dignity.',
    heartLessons: ['Name your pain without despair.', 'Mercy remains open in long trials.'],
    sources: [{ type: 'Qur\'an', reference: 'Al-Anbiya 21:83-84', note: 'Direct revealed source' }],
    recitationGuidance: 'Recite in times of illness and exhaustion with humility and trust.'
  },
  {
    slug: 'dua-of-yunus',
    title: 'Dua of Yunus عليه السلام',
    category: 'Hardship & Repentance',
    arabic: 'لَا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ',
    transliteration: 'La ilaha illa anta subhanaka inni kuntu minaz-zalimin',
    translationReadable: 'There is no god but You. You are perfect. I have wronged myself.',
    storyContext: 'Yunus عليه السلام called upon Allah in deep distress with tawhid, tasbih, and repentance.',
    heartLessons: ['Return begins with honesty.', 'Hope and accountability can coexist.'],
    sources: [{ type: 'Qur\'an', reference: 'Al-Anbiya 21:87-88', note: 'Direct revealed source' }],
    recitationGuidance: 'Recite in hardship, in sujood, and when seeking sincere return.'
  },
  {
    slug: 'hasbunallahu-wa-nimal-wakeel',
    title: 'Hasbunallahu wa ni‘mal wakeel',
    category: 'Tawakkul & Fear',
    arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
    transliteration: 'Hasbunallahu wa nimal wakeel',
    translationReadable: 'Allah is enough for us, and He is the best disposer of affairs.',
    storyContext: 'Believers said this when threatened and pressured by enemies.',
    heartLessons: ['Tawakkul means reliance with action.', 'Allah is enough in fear.'],
    sources: [{ type: 'Qur\'an', reference: 'Aal Imran 3:173', note: 'Direct revealed source' }],
    recitationGuidance: 'Recite when anxious about outcomes and opposition.'
  },
  {
    slug: 'wa-ufawwidu-amri-ilallah',
    title: 'Wa ufawwidu amri ilallah',
    category: 'Surrender',
    arabic: 'وَأُفَوِّضُ أَمْرِي إِلَى اللَّهِ',
    transliteration: 'Wa ufawwidu amri ilallah',
    translationReadable: 'I entrust my affair to Allah.',
    storyContext: 'Spoken by the believing man in Pharaoh’s court under threat.',
    heartLessons: ['Entrusting to Allah is strength.', 'Surrender is not passivity.'],
    sources: [{ type: 'Qur\'an', reference: 'Ghafir 40:44', note: 'Direct revealed source' }],
    recitationGuidance: 'Recite before difficult conversations and uncertain decisions.'
  },
  {
    slug: 'rabbi-inni-maghloobun-fantasir',
    title: 'Rabbi inni maghloobun fantasir',
    category: 'Relief in Distress',
    arabic: 'رَبِّ إِنِّي مَغْلُوبٌ فَانتَصِرْ',
    transliteration: 'Rabbi inni maghloobun fantasir',
    translationReadable: 'My Lord, I am overpowered, so help me.',
    storyContext: 'Nuh عليه السلام called Allah after prolonged rejection and hardship.',
    heartLessons: ['Short duas can carry immense sincerity.', 'Ask for help directly and humbly.'],
    sources: [{ type: 'Qur\'an', reference: 'Al-Qamar 54:10', note: 'Direct revealed source' }],
    recitationGuidance: 'Recite when emotionally overwhelmed and at your limit.'
  },
  {
    slug: 'la-ilaha-illallahul-azeemul-haleem',
    title: 'La ilaha illallahul azeemul haleem',
    category: 'Relief',
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ',
    transliteration: 'La ilaha illallahul azeemul haleem',
    translationReadable: 'There is no god but Allah, the Magnificent, the Forbearing.',
    storyContext: 'Reported among supplications in distress and difficulty.',
    heartLessons: ['Remembering Allah’s names calms the heart.', 'Relief begins with remembrance.'],
    sources: [{ type: 'Hadith', reference: 'Sahih al-Bukhari / Sahih Muslim', note: 'Authentic report in distress supplications' }],
    recitationGuidance: 'Recite in moments of fear and heaviness with reflection on Allah’s names.'
  },
  {
    slug: 'allahumma-inni-asaluka-ilman-nafian',
    title: 'Dua for Beneficial Knowledge and Rizq',
    category: 'Rizq & Growth',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا',
    transliteration: 'Allahumma inni asaluka ilman nafian wa rizqan tayyiban wa amalan mutaqabbalan',
    translationReadable: 'O Allah, I ask You for beneficial knowledge, good provision, and accepted deeds.',
    storyContext: 'A prophetic supplication taught for daily grounding in useful knowledge and lawful provision.',
    heartLessons: ['Ask for provision with purpose.', 'Rizq is tied to barakah and acceptance.'],
    sources: [{ type: 'Hadith', reference: 'Sunan Ibn Majah 925', note: 'Authentic/hasan by scholars' }],
    recitationGuidance: 'Recite in the morning and before work or study.'
  },
  {
    slug: 'bismillahilladhi-la-yadurru',
    title: 'Protection Dua (Morning/Evening)',
    category: 'Protection',
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ',
    transliteration: 'Bismillahilladhi la yadurru maasmihi shayun',
    translationReadable: 'In the name of Allah, with whose name nothing can cause harm.',
    storyContext: 'Prophetic remembrance for daily protection morning and evening.',
    heartLessons: ['Protection starts with remembrance.', 'Consistency builds spiritual resilience.'],
    sources: [{ type: 'Hadith', reference: 'Sunan Abi Dawud 5088', note: 'Hasan sahih grading by scholars' }],
    recitationGuidance: 'Recite morning and evening with attentiveness and trust.'
  },
  {
    slug: 'la-hawla-wa-la-quwwata',
    title: 'La hawla wa la quwwata illa billah',
    category: 'Surrender & Strength',
    arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: 'La hawla wa la quwwata illa billah',
    translationReadable: 'There is no power and no might except through Allah.',
    storyContext: 'A treasured phrase of remembrance emphasizing dependence on Allah.',
    heartLessons: ['Real strength is from Allah.', 'Release ego and lean into divine help.'],
    sources: [{ type: 'Hadith', reference: 'Sahih al-Bukhari 6384; Sahih Muslim 2704', note: 'Authentic' }],
    recitationGuidance: 'Recite when facing weakness, transitions, or difficult tasks.'
  },
  {
    slug: 'allahumma-rahmataka-arju',
    title: 'Dua in Emotional Overwhelm',
    category: 'Emotional Overwhelm & Mercy',
    arabic: 'اللَّهُمَّ رَحْمَتَكَ أَرْجُو فَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ',
    transliteration: 'Allahumma rahmataka arju fala takilni ila nafsi tarfata ayn',
    translationReadable: 'O Allah, I hope for Your mercy, so do not leave me to myself even for a blink.',
    storyContext: 'A prophetic plea for mercy and dependence during vulnerability.',
    heartLessons: ['Mercy is the believer’s refuge.', 'Self-reliance alone can break the heart.'],
    sources: [{ type: 'Hadith', reference: 'Sunan Abi Dawud 5090', note: 'Hasan by scholars' }],
    recitationGuidance: 'Recite during emotional heaviness and when feeling spiritually distant.'
  }
];
